# -*- coding: utf-8 -*-
"""basic_python_exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUt0DPXLyZoSv-P_1KiowukAjCNCdjNR

Welcome to this Python exercise set! These tasks will help you practice the basics of Python programming, from variables and simple arithmetic to control structures, loops, and file handling. Each exercise is designed to be completed in a few minutes, with helpful hints along the way.

Let’s get started!

# Exercise 1: Variables, data types, and basic arithmetic

We'll begin by working with basic variables and arithmetic.

**Task:**

1.   Create two variables, `a` and `b`, and assign them any integer values.
2.   Print the result of adding, subtracting, multiplying, and dividing `a` and `b`.
3.   Use an if statement to print whether `a` is greater than `b`.

## Hint

Use `if` and `else` to control the output based on a condition. Don’t forget to indent!

## Solution
"""

a = 7
b = 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)
if a > b:
    print("a is greater than b")
else:
    print("a is not greater than b")

"""# Exercise 2: Lists and loops

Now, let's work with lists and loops to iterate through data.

**Task:**

1.   Create a list of five of your favorite fruits.
2.   Use a `for` loop to print each fruit.
3.   Use an if statement inside the loop to print "I love this one!" when you reach your favorite fruit.

## Hint

A `for` loop allows you to iterate through each item in a list. Use `==` to compare values in an if statement.

## Solution
"""

fruits = ["apple", "banana", "cherry", "mango", "grape"]
for fruit in fruits:
    if fruit == "mango":
        print(fruit, "- I love this one!")
    else:
        print(fruit)

"""# Exercise 3: Dictionaries and loops

Dictionaries allow you to store key-value pairs. Let's practice accessing and modifying these pairs.

Task:

1.   Create a dictionary with three key-value pairs. Use a person's name as the key and their age as the value for each pair.
2.   Loop through the dictionary to print out each person's name and age.
3.   Modify the dictionary to add a new person and their age.

## Hint

Use [`.items()`](https://www.w3schools.com/python/ref_dictionary_items.asp) to loop through both the keys and values of a dictionary.

## Solution
"""

people = {"Alice": 30, "Bob": 25, "Charlie": 35}

for person in people:
  print(person, people[person])
  #Hi

people["Dave"] = 40
print(people)


"""# Exercise 4: Functions

Functions help you organize code into reusable blocks. Let's create one!

**Task:**

1.   Define a function `multiply_numbers` that takes two arguments, `x` and `y`.
2.   Inside the function, return the product of `x` and `y`.
3.   Call the function with two numbers and print the result.

## Hint

Use the `def` keyword to define a function, and `return` to send a value back from the function.

## Solution
"""

def multiply_numbers(x, y):
    return x * y

result = multiply_numbers(4, 5)
print(result)

"""# Exercise 5: Importing functions

Sometimes, you'll want to reuse code from other Python files or modules. Let's practice importing and using functions from built-in Python libraries.

**Task:**

1.   Import the `math` module.
2.   Use the `math.sqrt()` function to calculate and print the square root of a number.

## Hint

The math module contains many useful functions like `sqrt` for square roots and `pow` for exponentiation.

## Solution
"""

import math
print(math.sqrt(16))

"""# Exercise 6: Reading from and writing to files

Working with files is an essential part of programming. Let's practice reading and writing data to a file.

Task:

1.   Use Python to create a text file called `my_data.txt` and write three lines of text to it.
2.   Read the contents of the file and print each line.

## Hint

Use `open()` with mode `"w"` for writing and `"r"` for reading. Remember to use `.strip()` to remove extra whitespace or newline characters when printing lines from the file.

## Solution
"""

# Writing to a file
with open("my_data.txt", "w") as file:
    file.write("First line\n")
    file.write("Second line\n")
    file.write("Third line\n")

# Reading from a file
with open("my_data.txt", "r") as file:
    for line in file:
        print(line.strip())